In [32]:
#prac 9
import nltk
import re
from nltk.stem import PorterStemmer
import pandas as pd
nltk.download('stopwords')
from nltk.corpus import stopwords
sms_data=pd.read_csv("/content/spam.csv",encoding='latin-1')
stemming=PorterStemmer()
corpus=[]
for i in range(0,len(sms_data)):
  s1=re.sub(r'[^a-zA-z]',repl="",string=sms_data['v2'][i])
  s1.lower()
  s1=s1.split()
  s1=[stemming.stem(word)for word in s1 if word not in set(stopwords.words('english'))]
  s1="".join(s1)
  corpus.append(s1)

from sklearn.feature_extraction.text import CountVectorizer
countvectorizer=CountVectorizer()
x=countvectorizer.fit_transform(corpus).toarray()
print(x)
y = sms_data['v1'].values
print(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2,stratify=y)

from sklearn.naive_bayes import MultinomialNB
multinomialnb=MultinomialNB()
multinomialnb.fit(x_train,y_train)
multinomialnb.fit(x_train,y_train)

y_pred=multinomialnb.predict(x_test)
print(y_pred)

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
print(classification_report(y_test,y_pred))
print("accuracy_score: ",accuracy_score(y_test,y_pred))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']
['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']
              precision    recall  f1-score   support

         ham       0.87      1.00      0.93      1448
        spam       0.71      0.02      0.04       224

    accuracy                           0.87      1672
   macro avg       0.79      0.51      0.49      1672
weighted avg       0.85      0.87      0.81      1672

accuracy_score:  0.867822966507177


In [ ]:
#10 speech tagging using spacy
import spacy
from spacy import displacy
sp=spacy.load('en_core_web_sm')
sen=sp(u'I like to play football. I hated it in my childhood though.')
print(sen.text)
print(sen[7].pos_)
print(sen[7].tag_)
print(spacy.explain(sen[7].tag_))
for word in sen:
  print(f'{word.text:{12}},{word.pos_:{10}},{word.tag_:{8}},{spacy.explain(word.tag_)}')
  sen=sp(u"You can google it?")
  word=sen[2]

  print(f'{word.text:{12}},{word.pos_:{10}},{word.tag_:{8}},{spacy.explain(word.tag_)}')
  sen=sp(u"You can search it on google")
  word=sen[5]
  
  print(f'{word.text:{12}},{word.pos_:{10}},{word.tag_:{8}},{spacy.explain(word.tag_)}')
  num_pos=sen.count_by(spacy.attrs.POS)
for k,v in sorted(num_pos.items()):
  print(f'{k}.{sen.vocab[k].text:{8}}:{v}')
sen=sp(u'I like to play football. I hated it in my childhood though.')
displacy.serve(sen)

I like to play football. I hated it in my childhood though.
VERB
VBD
verb, past tense
I           ,PRON      ,PRP     ,pronoun, personal
google      ,VERB      ,VB      ,verb, base form
google      ,PROPN     ,NNP     ,noun, proper singular
like        ,VERB      ,VBP     ,verb, non-3rd person singular present
google      ,VERB      ,VB      ,verb, base form
google      ,PROPN     ,NNP     ,noun, proper singular
to          ,PART      ,TO      ,infinitival "to"
google      ,VERB      ,VB      ,verb, base form
google      ,PROPN     ,NNP     ,noun, proper singular
play        ,VERB      ,VB      ,verb, base form
google      ,VERB      ,VB      ,verb, base form
google      ,PROPN     ,NNP     ,noun, proper singular
football    ,NOUN      ,NN      ,noun, singular or mass
google      ,VERB      ,VB      ,verb, base form
google      ,PROPN     ,NNP     ,noun, proper singular
.           ,PUNCT     ,.       ,punctuation mark, sentence closer
google      ,VERB      ,VB      ,verb, base form
g

In [17]:
#speech tagging using nltk
import nltk
from nltk.corpus import state_union
nltk.download('punkt')
nltk.download('state_union')
from nltk.tokenize import PunktSentenceTokenizer
train_text=state_union.raw("2005-GWBush.txt")
sample_text=state_union.raw('2006-GWBush.txt')
custom_set_tokenizer=PunktSentenceTokenizer(train_text)
tokenized=custom_set_tokenizer.tokenize(sample_text)
def process_content():
  try:
    for word in tokenized:
      words=nltk.word_tokenize(i)
      tagged=nltk.pos_tag(words)
      print(tagged)
  except Exception as e:
    print(str(e))
process_content()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package state_union to /root/nltk_data...
[nltk_data]   Package state_union is already up-to-date!
expected string or bytes-like object


In [ ]:
# usage of give and gave in penn tree ban
import nltk
nltk.download('treebank')
def give(t):
  return t.label()=='VP' and len(t)>2 and t[1].label()=='NP'and(t[2].label()=='PP-DTV' or t[2].label()=='NP') and('give' in t[0].leaves() or 'gave' in t[0].leaves())
def sent(t):
  return "".join(token for token in t.leaves() if token[0] not in '*-0')
def print_node(t,width):
  output="%s%s:%s/%s:%s"%(sent(t[0]),t[1].label(),sent(t[1]),t[2].label(),sent(t[2]))
  if len(output)>width:
    output=output[:width]+"......"
    print(output)
for tree in nltk.corpus.treebank.parsed_sents():
  for t in tree.subtrees(give):
    print_node(t,72)


In [ ]:
import nltk
from nltk import ViterbiParser
from nltk import PCFG
grammar=PCFG.fromstring('''
NP -> NNS[0.5] |JJ NNS[0.3]|NP CC NP[0.2]
NNS -> "man"[0.1]|"women"[0.2]|children[0.3]|NNS CC NNS[0.4]
JJ -> "old"[0.4]|"young"[0.6]
CC -> "and"[0.9]|"or"[0.1]
''')
print(grammar)
parser=ViterbiParser(grammar)
sen="old man and young women".split()
#text=nltk.tokenize.word_tokenize(sen)
x=parser.parse(sen)
for i in x:
  print(i)

In [ ]:
from nltk.parse import malt
mp=malt.MaltParser('maltparser-1.7.2','engmalt.linear-1.7.mco')
t=malt.parse_onr("I saw a bird from my window".split()).tree
print(t)
t.draw()

In [31]:
#prac 11 mwe tokenizer
from nltk.tokenize import MWETokenizer
from nltk import sent_tokenize,word_tokenize
s="Good cake costs Rs.1500\kg in Mumbai. Please buy me one of them. \n\n Thanks"
mwe=MWETokenizer()
for sent in sent_tokenize(s):
  print(mwe.tokenize(word_tokenize(sent)))

['Good', 'cake', 'costs', 'Rs.1500\\kg', 'in', 'Mumbai', '.']
['Please', 'buy', 'me', 'one', 'of', 'them', '.']
['Thanks']


In [39]:
#Normalized web distance and word similarity
!pip install textdistance
import numpy as np
import re 
import textdistance

from sklearn.cluster import AgglomerativeClustering
texts=['Reliance supermarket','Reliance hypermarket','Reliance','Reliance down town','relianc market','Reliance downtown','Mumbai','Mumbai Hyper','Mumbai dxb','mumbai airport','k.m trading','K.M. Trading','KM. Trading']

def normalize(text):
  return re.sub('[^a-z0-9]+','',text.lower())
def group_texts(texts,threshold=0.4):
  normalized_texts=np.array([normalize(text)for text in texts])
  distances=1-np.array([[textdistance.jaro_winkler(one,another)for one in normalized_texts]for another in normalized_texts])
  clustering=AgglomerativeClustering(distance_threshold=threshold,affinity='precomputed',linkage='complete',n_clusters=None).fit(distances)
  centers=dict()
  for cluster_id in set(clustering.labels_):
    index=clustering.labels_==cluster_id
    centrality=distances[:,index][index].sum(axis=1)
    centers[cluster_id]=normalized_texts[index][centrality.argmin()]
  return[centers[i] for i in clustering.labels_]
print(group_texts(texts))


['reliance', 'reliance', 'reliance', 'reliance', 'reliance', 'reliance', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'kmtrading', 'kmtrading', 'kmtrading']


In [44]:
#word sense disambiguation
from nltk.corpus import wordnet as wn
nltk.download('wordnet')
def get_first_sense(word,pos=None):
  if pos:
    synsets=wn.synsets(word,pos)
  else:
    synsets=wn.synsets(word)
  return synsets[0]

best_synset=get_first_sense("bank")
print("%s:%s"%(best_synset.name,best_synset.definition))
best_synset=get_first_sense("set",'n')
print("%s:%s"%(best_synset.name,best_synset.definition))
best_synset=get_first_sense("set",'v')
print("%s:%s"%(best_synset.name,best_synset.definition))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
<bound method Synset.name of Synset('bank.n.01')>:<bound method Synset.definition of Synset('bank.n.01')>
<bound method Synset.name of Synset('set.n.01')>:<bound method Synset.definition of Synset('set.n.01')>
<bound method Synset.name of Synset('put.v.01')>:<bound method Synset.definition of Synset('put.v.01')>
